# Generated by Django 5.2.14 on 2026-06-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_attendancerecord_id_alter_lastface_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
