# Generated by Django 5.2.14 on 2026-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_profile_department_profile_shift_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="working_hours",
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
