# Generated by Django 6.0.4 on 2026-06-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_profile_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="face_encoding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lastface",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
