# Generated by Django 6.0.4 on 2026-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_profile_face_encoding_alter_attendancerecord_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ranking",
            field=models.IntegerField(default=0),
        ),
    ]
